import os
import random
import re
import sys

DAMPING = 0.85
SAMPLES = 10000


def main():
    if len(sys.argv) != 2:
        sys.exit("Usage: python pagerank.py corpus")
    corpus = crawl(sys.argv[1])
    ranks = sample_pagerank(corpus, DAMPING, SAMPLES)
    print(f"PageRank Results from Sampling (n = {SAMPLES})")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")
    ranks = iterate_pagerank(corpus, DAMPING)
    print(f"PageRank Results from Iteration")
    for page in sorted(ranks):
        print(f"  {page}: {ranks[page]:.4f}")


def crawl(directory):
    """
    Parse a directory of HTML pages and check for links to other pages.
    Return a dictionary where each key is a page, and values are
    a list of all other pages in the corpus that are linked to by the page.
    """
    pages = dict()

    # Extract all links from HTML files
    for filename in os.listdir(directory):
        if not filename.endswith(".html"):
            continue
        with open(os.path.join(directory, filename)) as f:
            contents = f.read()
            links = re.findall(r"<a\s+(?:[^>]*?)href=\"([^\"]*)\"", contents)
            pages[filename] = set(links) - {filename}

    # Only include links to other pages in the corpus
    for filename in pages:
        pages[filename] = set(
            link for link in pages[filename]
            if link in pages
        )

    return pages


def transition_model(corpus, page, damping_factor):
    """
    Return a probability distribution over which page to visit next,
    given a current page.

    With probability `damping_factor`, choose a link at random
    linked to by `page`. With probability `1 - damping_factor`, choose
    a link at random chosen from all pages in the corpus.
    """
    dico = dict()
    # Number of page in the corpus
    N = len(corpus)
    # Number of link on the current page
    Nlink = len(corpus[page])

    # If page has no outgoing links
    if Nlink == 0:
        # A probability distribution that chooses randomly among all pages with equal probability.
        for x in corpus:
            dico[x] = 1 / N

    # Else if page has a outgoing links
    else:
        for x in corpus:
            # With probability 1 - damping_factor, the random surfer randomly choose one of all pages in the corpus with equal probability.
            dico[x] = (1 - damping_factor) / N
            # With probability damping_factor, the random surfer should randomly choose one of the links from page with equal probability.
            if x in corpus[page]:
                dico[x] = dico[x] + (damping_factor / Nlink)

    return dico

def sample_pagerank(corpus, damping_factor, n):
    """
    Return PageRank values for each page by sampling `n` pages
    according to transition model, starting with a page at random.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    spdico = dict()
    # A empty list, will receive list of the pages in the corpus
    pglist = list()
    # Pages with the highest propapility
    maxhtml = list()

    for x in corpus:
        spdico.update({x : 0})

    # Make list of the pages in the corpus
    for x in corpus:
        pglist.append(x)

    # The first sample generated by choosing from a page at random.
    rpage = random.choice(pglist)

    for i in range(n - 1):

        ndic = transition_model(corpus, rpage, damping_factor)

        pmax = max( ndic.values() )

        # List of page with highest probability to be the next
        for x in ndic:
            if ndic.get(x) == pmax:
                maxhtml.append(x)
        # Choose randomly one the page with the highest probability to be the next
        rpage = random.choice(maxhtml)


        for x in ndic:
            pbblt = ndic.get(x)
            spdico[x] = spdico[x] + pbblt

    for x in spdico:
        spdico[x] = spdico[x] / n


    return spdico




def iterate_pagerank(corpus, damping_factor):
    """
    Return PageRank values for each page by iteratively updating
    PageRank values until convergence.

    Return a dictionary where keys are page names, and values are
    their estimated PageRank value (a value between 0 and 1). All
    PageRank values should sum to 1.
    """
    itdico = dict()
    # Number of page in the corpus
    N = len(corpus)

    # Add the pages in the corpus to the dictionnnary and Begin by assigning each page a rank of 1 / N
    for p in corpus:
        itdico.update({p : 1/N})

    this = bool

    while this:
        Citdico = itdico.copy()
        for p in corpus:
            sigma = 0
            for y in corpus:
                yNumLinks = len(corpus.get(y))
                if yNumLinks == 0:
                    yNumLinks = N
                PPr = 0
                # If y links to page p,
                if p in corpus.get(y):
                    PPr = itdico.get(y)

                sigma = sigma + (PPr / yNumLinks)

            itdico.update({p : (1 - damping_factor) / N + damping_factor * sigma })

        rptdico = dict()
        for p in corpus:
            rptdico.update({p : 0})

        # Check if each PageRank value changes by more than 0.001 between the current rank values and the new rank values and keep track of the result in rptdico
        for x in itdico:
            rptdico[x] = (itdico.get(x) - Citdico.get(x)) <= 0.001
        # If all Pagerank value changes by less than 0.001, --> end of the while loop
        if all (rptdico.values()):
            this = False

    return itdico


if __name__ == "__main__":
    main()
